name: on-push
on: [push]
env:
  MIX_ENV: test
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1
        with:
          otp-version: '23.0.4'
          elixir-version: '1.10.4'
      - uses: rrainn/dynamodb-action@v2.0.0
        with:
            port: 8000
            cors: '*'
      - run: mix deps.get
      - run: mix compile
      - run: epmd -daemon
      - run: mix test
